//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Globalization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Rule {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Rule() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Globalization.Rule", typeof(Rule).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Account.
        /// </summary>
        public static string AccountCurrent {
            get {
                return ResourceManager.GetString("AccountCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Account Plus.
        /// </summary>
        public static string AccountCurrentPlus {
            get {
                return ResourceManager.GetString("AccountCurrentPlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Junior Saver Account.
        /// </summary>
        public static string AccountJuniorSaver {
            get {
                return ResourceManager.GetString("AccountJuniorSaver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Account.
        /// </summary>
        public static string AccountStudent {
            get {
                return ResourceManager.GetString("AccountStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classic.
        /// </summary>
        public static string BundleClassic {
            get {
                return ResourceManager.GetString("BundleClassic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classic Plus.
        /// </summary>
        public static string BundleClassicPlus {
            get {
                return ResourceManager.GetString("BundleClassicPlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gold.
        /// </summary>
        public static string BundleGold {
            get {
                return ResourceManager.GetString("BundleGold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bundle is not suited for this customer.
        /// </summary>
        public static string BundleIsNotSuitedForThisCustomer {
            get {
                return ResourceManager.GetString("BundleIsNotSuitedForThisCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Junior Saver.
        /// </summary>
        public static string BundleJuniorSaver {
            get {
                return ResourceManager.GetString("BundleJuniorSaver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student.
        /// </summary>
        public static string BundleStudent {
            get {
                return ResourceManager.GetString("BundleStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit card.
        /// </summary>
        public static string CardCredit {
            get {
                return ResourceManager.GetString("CardCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debit card.
        /// </summary>
        public static string CardDebit {
            get {
                return ResourceManager.GetString("CardDebit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gold Credit card.
        /// </summary>
        public static string CardGoldCredit {
            get {
                return ResourceManager.GetString("CardGoldCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer age is not supplied.
        /// </summary>
        public static string CustomerAgeIsNotSupplied {
            get {
                return ResourceManager.GetString("CustomerAgeIsNotSupplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer answers are not supplied.
        /// </summary>
        public static string CustomerAnswersAreNotSupplied {
            get {
                return ResourceManager.GetString("CustomerAnswersAreNotSupplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer can&apos;t have more than one account.
        /// </summary>
        public static string CustomerCantHaveMoreThanOneAccount {
            get {
                return ResourceManager.GetString("CustomerCantHaveMoreThanOneAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer income is not supplied.
        /// </summary>
        public static string CustomerIncomeIsNotSupplied {
            get {
                return ResourceManager.GetString("CustomerIncomeIsNotSupplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer name is not supplied.
        /// </summary>
        public static string CustomerNameIsNotSupplied {
            get {
                return ResourceManager.GetString("CustomerNameIsNotSupplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debit card can not be added because no account was found for this customer.
        /// </summary>
        public static string DebitCardCanNotBeAddedBecauseNoAccountWasFoundForThisCustomer {
            get {
                return ResourceManager.GetString("DebitCardCanNotBeAddedBecauseNoAccountWasFoundForThisCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No bundle found by such name.
        /// </summary>
        public static string NoBundleFoundBySuchName {
            get {
                return ResourceManager.GetString("NoBundleFoundBySuchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product is not suitable for this customer.
        /// </summary>
        public static string ProductIsNotSuitableForThisCustomer {
            get {
                return ResourceManager.GetString("ProductIsNotSuitableForThisCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The bundle includes products, which are not suited for this customer. These products are: {0}.
        /// </summary>
        public static string ProductsNotSuitedForBundle {
            get {
                return ResourceManager.GetString("ProductsNotSuitedForBundle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested bundle is suitable for this customer.
        /// </summary>
        public static string RequestedBundleIsSuitableForThisCustomer {
            get {
                return ResourceManager.GetString("RequestedBundleIsSuitableForThisCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age &lt; 18.
        /// </summary>
        public static string RuleAgeLessThan18 {
            get {
                return ResourceManager.GetString("RuleAgeLessThan18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age &gt; 17.
        /// </summary>
        public static string RuleAgeMoreThan17 {
            get {
                return ResourceManager.GetString("RuleAgeMoreThan17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income &gt; 0.
        /// </summary>
        public static string RuleIncomeMoreThan0 {
            get {
                return ResourceManager.GetString("RuleIncomeMoreThan0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income &gt; 12000.
        /// </summary>
        public static string RuleIncomeMoreThan12000 {
            get {
                return ResourceManager.GetString("RuleIncomeMoreThan12000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income &gt; 40000.
        /// </summary>
        public static string RuleIncomeMoreThan40000 {
            get {
                return ResourceManager.GetString("RuleIncomeMoreThan40000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student = Yes.
        /// </summary>
        public static string RuleIsStudent {
            get {
                return ResourceManager.GetString("RuleIsStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no suitable bundle.
        /// </summary>
        public static string ThereIsNoSuitableBundle {
            get {
                return ResourceManager.GetString("ThereIsNoSuitableBundle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled error has occured.
        /// </summary>
        public static string UnhandledErrorHasOccured {
            get {
                return ResourceManager.GetString("UnhandledErrorHasOccured", resourceCulture);
            }
        }
    }
}
